-- Чек как сущность: кассовая смена, чек, его строки, заказы и платежи.
--
-- До этой миграции «оплачено» было одной колонкой `orders.status`: ни суммы,
-- ни метода, ни того, кто принял деньги. Для кассы этого мало — X- и Z-отчёты
-- считаются по платежам, а не по заказам.
--
-- Три решения, заложенные в схему:
--
-- 1. Чек ссылается на набор заказов (`receipt_orders`), а не на «сессию стола»:
--    сущности «визит» в базе нет, состав стола собирается из сегодняшних
--    незакрытых заказов. Номер стола чек хранит снимком — пересадка и
--    объединение не должны переписывать вчерашний чек.
-- 2. Строки чека — снимок (`receipt_items`), как это уже делает `order_items`
--    для заказа. Иначе правка меню перепишет прошлую выручку задним числом.
-- 3. Метод оплаты живёт в строках `receipt_payments`, а не в чеке: «часть
--    налом, часть картой» — это несколько платежей на один чек. Возврат тем же
--    приёмом становится платежом с отрицательной суммой, и «сумма возвратов»
--    для X-отчёта считается тем же запросом, что и выручка.

-- Канал заказа. Раньше «нет стола» означало выдачу, а доставку от самовывоза
-- отличала строка в `deliveries`. С заказом у стойки развилка стала третьей —
-- проще спросить сам заказ, чем гадать по связям.
alter table public.orders
  add column if not exists channel text not null default 'dine_in'
  check (channel in ('dine_in', 'delivery', 'pickup', 'counter'));

update public.orders o
set channel = d.kind
from public.deliveries d
where d.order_id = o.id and o.channel = 'dine_in';

create table if not exists public.cash_shifts (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants (id),
  cashier_id uuid not null references public.staff (id),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  -- Сколько наличных в ящике на начало смены и сколько насчитали в конце:
  -- расхождение — это и есть результат инкассации, его нельзя вычислить.
  cash_start numeric not null default 0 check (cash_start >= 0),
  cash_counted numeric check (cash_counted >= 0),
  note text
);

-- Открытая смена в ресторане ровно одна: две кассы в одном зале — это уже
-- другой разговор, и он потребует привязки чека к рабочему месту.
create unique index if not exists cash_shifts_one_open
  on public.cash_shifts (restaurant_id)
  where closed_at is null;

create table if not exists public.receipts (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants (id),
  number bigint generated by default as identity unique,
  cash_shift_id uuid references public.cash_shifts (id),
  cashier_id uuid references public.staff (id),
  -- Снимок: чек — документ, он не следует за пересадкой стола.
  table_number text,
  channel text not null default 'dine_in'
    check (channel in ('dine_in', 'delivery', 'pickup', 'counter')),
  subtotal numeric not null default 0 check (subtotal >= 0),
  discount numeric not null default 0 check (discount >= 0),
  discount_reason text,
  tip numeric not null default 0 check (tip >= 0),
  total numeric not null default 0 check (total >= 0),
  status text not null default 'open' check (status in ('open', 'paid', 'void', 'refunded')),
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists receipts_shift_idx on public.receipts (cash_shift_id);
create index if not exists receipts_created_idx on public.receipts (created_at desc);

create table if not exists public.receipt_orders (
  receipt_id uuid not null references public.receipts (id) on delete cascade,
  order_id uuid not null references public.orders (id),
  primary key (receipt_id, order_id)
);

create table if not exists public.receipt_items (
  id uuid primary key default gen_random_uuid(),
  receipt_id uuid not null references public.receipts (id) on delete cascade,
  title text not null,
  options text,
  modifiers text,
  quantity integer not null check (quantity > 0),
  unit_price numeric not null check (unit_price >= 0),
  sort_order integer not null default 0
);

create index if not exists receipt_items_receipt_idx on public.receipt_items (receipt_id);

create table if not exists public.receipt_payments (
  id uuid primary key default gen_random_uuid(),
  receipt_id uuid not null references public.receipts (id) on delete cascade,
  method text not null check (method in ('cash', 'card', 'qr')),
  -- Отрицательная сумма — возврат: отдельного статуса он не требует, а в отчёт
  -- попадает тем же запросом, что и выручка.
  amount numeric not null,
  change_given numeric not null default 0 check (change_given >= 0),
  provider_ref text,
  status text not null default 'paid' check (status in ('pending', 'paid', 'failed')),
  created_at timestamptz not null default now()
);

create index if not exists receipt_payments_receipt_idx on public.receipt_payments (receipt_id);

-- Закрытый чек не редактируется. Ошиблись — оформляется возврат или чек
-- аннулируется целиком: правка задним числом делает отчёт бессмысленным.
create or replace function public.guard_closed_receipt()
returns trigger
language plpgsql
as $$
begin
  if old.status in ('paid', 'void', 'refunded') and new.status = old.status then
    raise exception 'Закрытый чек №% изменять нельзя', old.number;
  end if;
  return new;
end;
$$;

drop trigger if exists receipts_guard_closed on public.receipts;
create trigger receipts_guard_closed
before update on public.receipts
for each row execute function public.guard_closed_receipt();

alter table public.cash_shifts enable row level security;
alter table public.receipts enable row level security;
alter table public.receipt_orders enable row level security;
alter table public.receipt_items enable row level security;
alter table public.receipt_payments enable row level security;

-- Деньги видит и трогает только персонал. Аноним (гостевое меню) сюда
-- не ходит вовсе: чек ему показывает касса или официант.
do $$
declare
  t text;
begin
  foreach t in array array['cash_shifts', 'receipts', 'receipt_orders', 'receipt_items', 'receipt_payments']
  loop
    execute format('drop policy if exists "staff reads %1$s" on public.%1$I', t);
    execute format('drop policy if exists "staff writes %1$s" on public.%1$I', t);
    execute format(
      'create policy "staff reads %1$s" on public.%1$I for select to authenticated using (public.is_staff())', t);
    execute format(
      'create policy "staff writes %1$s" on public.%1$I for insert to authenticated with check (public.is_staff())', t);
  end loop;
end;
$$;

drop policy if exists "staff updates receipts" on public.receipts;
create policy "staff updates receipts" on public.receipts
  for update to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists "staff updates cash shifts" on public.cash_shifts;
create policy "staff updates cash shifts" on public.cash_shifts
  for update to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists "staff updates receipt payments" on public.receipt_payments;
create policy "staff updates receipt payments" on public.receipt_payments
  for update to authenticated using (public.is_staff()) with check (public.is_staff());
